# Generated by Django 3.0.6 on 2020-05-09 07:56

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200508_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscomment',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(null=True, upload_to=news.models.upload_img_file),
        ),
    ]
