# Generated by Django 3.0.6 on 2020-05-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200509_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cover',
        ),
    ]
