# Generated by Django 3.0.6 on 2020-05-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
