# Generated by Django 3.0.6 on 2020-05-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200509_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
