# Generated by Django 3.0.6 on 2020-05-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_is_breaking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscomment',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='up_votes',
        ),
    ]
