# Generated by Django 3.0.6 on 2020-05-09 07:56

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200508_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to=team.models.upload_img_file),
        ),
    ]
