# Generated by Django 3.0.6 on 2020-05-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name': 'Player stats', 'verbose_name_plural': 'Player stats'},
        ),
        migrations.AddField(
            model_name='player',
            name='birth_city',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('PLAYER', 'Pl'), ('GOALKEEPER', 'Gk'), ('RIGHT BACK', 'Rb'), ('CENTRAL BACK', 'Cb'), ('LEFT BACK', 'Lb'), ('DEFENSIVE MIDFIELDER', 'Dm'), ('CENTRAL MIDFIELDER', 'Cmf'), ('LEFT MIDFIELDER', 'Lmf'), ('RIGHT MIDFIELDER', 'Rmf'), ('ATTACKING MIDFIELDER', 'Amf'), ('STRIKER', 'St')], default='PLAYER', max_length=255),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='assists',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstats',
            name='avr_score',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstats',
            name='games',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstats',
            name='goals',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstats',
            name='season',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
