# Generated by Django 3.0.6 on 2020-05-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
            preserve_default=False,
        ),
    ]
