# Generated by Django 3.0.6 on 2020-05-09 07:56

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200508_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to=blog.models.upload_img_file),
        ),
    ]
