# Generated by Django 3.0.6 on 2020-05-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
