# Generated by Django 3.0.6 on 2020-05-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200509_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='up_votes',
        ),
    ]
