# Generated by Django 3.0.6 on 2020-05-08 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('b10f6a8a-ca05-48d6-9f40-6594e66626f9'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_confirmed',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('NOT_CONFIRMED', 'Not Confirmed')], default='NOT_CONFIRMED', max_length=255),
        ),
    ]
