# Generated by Django 3.0.6 on 2020-05-08 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200508_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('e65fd16c-9964-43b7-a264-24234d819bf3'), editable=False),
        ),
    ]
