# Generated by Django 3.0.6 on 2020-05-08 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200508_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('a86cc8da-ef44-453c-96a4-5f6ff4187304'), editable=False),
        ),
    ]
