# Generated by Django 3.0.6 on 2020-05-08 17:58

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200508_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='no name', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('353b31a2-e7a2-4a1a-9dde-ac84dabb3abd'), editable=False),
        ),
    ]
