# Generated by Django 3.0.6 on 2020-05-08 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200508_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('78c4e320-2c9f-45ec-8e70-2e4322aaa0e8'), editable=False),
        ),
    ]
