# Generated by Django 3.0.6 on 2020-05-08 18:03

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200508_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('8c503587-c376-46f8-bf71-491c0654569f'), editable=False),
        ),
    ]
