# Generated by Django 3.0.6 on 2020-05-09 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200509_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('61c067d9-2a71-48de-ba8d-5d2b1514f0e8'), editable=False),
        ),
    ]
