# Generated by Django 3.0.6 on 2020-05-09 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200509_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('0ae1069f-5537-4a49-ab0d-222c04b9ad3c'), editable=False),
        ),
    ]
