# Generated by Django 3.0.6 on 2020-05-09 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200509_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('a88bc63d-be14-42e4-b163-eb77f5d65dad'), editable=False),
        ),
    ]
