# Generated by Django 3.0.6 on 2020-05-09 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200509_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('0aa7921e-e432-414a-b149-fbc50d8f0678'), editable=False),
        ),
    ]
