# Generated by Django 3.0.6 on 2020-05-09 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20200509_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('ccd8cdef-da74-4471-a3a7-32addbf8f79c'), editable=False),
        ),
    ]
