# Generated by Django 3.0.6 on 2020-05-12 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20200509_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('c5c79109-4154-4803-b9e4-411a2c848cfb'), editable=False),
        ),
    ]
