# Generated by Django 3.0.6 on 2020-05-13 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200512_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('07e05ac3-1419-4f2d-a3f5-2c45622f86dd'), editable=False),
        ),
    ]
