# Generated by Django 3.0.6 on 2020-05-13 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200513_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('d3191917-d5cc-4d5f-912d-5727814ec9b2'), editable=False),
        ),
    ]
